# Generated by Django 2.2.5 on 2019-10-22 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='CO',
            fields=[
                ('CO_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Outcome', models.TextField(max_length=500)),
                ('assignments', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('units', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('insem', models.BooleanField()),
                ('endsem', models.BooleanField()),
                ('practicle', models.BooleanField()),
                ('TW', models.BooleanField()),
            ],
            options={
                'db_table': 'co',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('course', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('CourseName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('course', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('po', models.TextField()),
            ],
            options={
                'db_table': 'po',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=30)),
                ('t_contact', models.BigIntegerField()),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_weight', models.FloatField()),
                ('ext_weight', models.FloatField(choices=[(0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1.0, 1.0)])),
                ('target', models.IntegerField()),
                ('Code_patt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.Employee', unique=True)),
            ],
            options={
                'db_table': 'weights',
            },
        ),
        migrations.CreateModel(
            name='Upload_Int',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.FloatField(default=0)),
                ('A2', models.FloatField(default=0)),
                ('A3', models.FloatField(default=0)),
                ('A4', models.FloatField(default=0)),
                ('A5', models.FloatField(default=0)),
                ('ut1', models.FloatField(default=0)),
                ('ut2', models.FloatField(default=0)),
                ('ut3', models.FloatField(default=0)),
                ('ut4', models.FloatField(default=0)),
                ('ut5', models.FloatField(default=0)),
                ('tw', models.FloatField(default=0)),
                ('Code_patt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.Employee')),
            ],
            options={
                'db_table': 'upload',
            },
        ),
        migrations.CreateModel(
            name='Upload_Ext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insem', models.FloatField()),
                ('endsem', models.FloatField()),
                ('practicals', models.FloatField()),
                ('TW', models.FloatField(blank=True, null=True)),
                ('Code_patt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.Employee')),
            ],
            options={
                'db_table': 'upload1',
            },
        ),
        migrations.CreateModel(
            name='TeachingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.CharField(max_length=5)),
                ('practicle', models.CharField(max_length=5)),
                ('tutorial', models.CharField(max_length=5)),
                ('Code_patt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.Employee', unique=True)),
            ],
            options={
                'db_table': 'teachingscheme',
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=20)),
                ('sem', models.IntegerField()),
                ('A_Y', models.IntegerField()),
                ('Code_patt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.Employee')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.Teacher')),
            ],
            options={
                'db_table': 'teaches',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=20)),
                ('assessment', models.FloatField()),
                ('Y_N', models.CharField(max_length=3)),
                ('VPO1', models.FloatField(blank=True, null=True)),
                ('VPO2', models.FloatField(blank=True, null=True)),
                ('VPO3', models.FloatField(blank=True, null=True)),
                ('VPO4', models.FloatField(blank=True, null=True)),
                ('VPO5', models.FloatField(blank=True, null=True)),
                ('VPO6', models.FloatField(blank=True, null=True)),
                ('VPO7', models.FloatField(blank=True, null=True)),
                ('VPO8', models.FloatField(blank=True, null=True)),
                ('VPO9', models.FloatField(blank=True, null=True)),
                ('VPO10', models.FloatField(blank=True, null=True)),
                ('VPO11', models.FloatField(blank=True, null=True)),
                ('VPO12', models.FloatField(blank=True, null=True)),
                ('CO_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tem.CO')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='ExamScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onlineinsem', models.IntegerField(blank=True, null=True)),
                ('endsem', models.IntegerField(blank=True, null=True)),
                ('termwork', models.IntegerField(blank=True, null=True)),
                ('Practicle', models.IntegerField(blank=True, null=True)),
                ('oral', models.IntegerField(blank=True, null=True)),
                ('Code_patt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.Employee', unique=True)),
            ],
            options={
                'db_table': 'examscheme',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalktalk', models.BooleanField()),
                ('ict', models.BooleanField()),
                ('gd', models.BooleanField()),
                ('ifv', models.BooleanField()),
                ('et', models.BooleanField()),
                ('sur', models.BooleanField()),
                ('mp', models.BooleanField()),
                ('lab', models.BooleanField()),
                ('Code_patt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.Employee')),
            ],
            options={
                'db_table': 'deliverymethods',
            },
        ),
        migrations.CreateModel(
            name='CoPoMapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VPO1', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO2', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO3', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO4', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO5', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO6', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO7', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO8', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO9', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO10', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO11', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('VPO12', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('CO_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tem.CO')),
            ],
            options={
                'db_table': 'copomapp',
            },
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.FloatField(default=0)),
                ('practicle', models.FloatField(default=0)),
                ('termwork', models.FloatField(default=0)),
                ('unittests', models.FloatField(default=0)),
                ('insem', models.FloatField(default=0)),
                ('endsem', models.FloatField(default=0)),
                ('assessment', models.FloatField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('CO_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tem.CO')),
            ],
            options={
                'db_table': 'assesment',
            },
        ),
    ]
