# Generated by Django 2.2.5 on 2019-12-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copomapp',
            old_name='CO_id',
            new_name='COid',
        ),
        migrations.AlterField(
            model_name='examscheme',
            name='Code_patt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tem.Employee'),
        ),
        migrations.AlterField(
            model_name='teachingscheme',
            name='Code_patt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tem.Employee'),
        ),
        migrations.AlterField(
            model_name='weights',
            name='Code_patt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tem.Employee'),
        ),
    ]
