# Generated by Django 2.2.5 on 2019-12-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0002_auto_20191211_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copomapp',
            old_name='COid',
            new_name='CO_id',
        ),
    ]
