# Generated by Django 2.2.5 on 2019-12-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0004_auto_20191211_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymethods',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weights',
            name='id',
        ),
        migrations.AlterField(
            model_name='deliverymethods',
            name='Code_patt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tem.Employee'),
        ),
        migrations.AlterField(
            model_name='weights',
            name='Code_patt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tem.Employee'),
        ),
    ]
