# Generated by Django 2.2.5 on 2019-12-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0005_auto_20191217_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copomapp',
            name='CO_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tem.CO'),
        ),
    ]
